name: Trolling
main: me.groot314.Trolling.Trolling
version: 1.0
commands:
  trolling:
    description: Displays Trollings Commands
    usage: /trolling
  trollKill:
    description: Troll Kills a player
    usage: /trollkill
  trollKick:
    description: Troll kicks a Player.
    usage: /trollKick <Player>
  launch:
    description: Launches a player in the air
    usage: /launch

permissions:
  trolling.kick:
    description: Allows a player to Troll kick a player
    default: OP
  trolling.kill:
    description: Allows a player to Troll kill a player
    default: OP
  trolling.launch
    description: Allows a player to Launch a player
    default: OP