name: Trolling
main: me.groot314.Trolling.Trolling
version: 1.0
commands:
  trolling:
    description: Displays Trollings Commands
    usage: /trolling
  trollKill:
    description: Troll Kills a player
    usage: /trollkill
  trollKick:
    description: Troll kicks a Player.
    usage: /trollKick <Player>

permissions:
  trolling.kick
    description: Troll kicks a player
    default: OP
  trolling.kill
    description: Troll kills a player
    default: OP